import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.application'
    id 'kotlin-parcelize'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}

if (file("${rootProject.rootDir}/environment.properties").exists()) {
    apply from: "${rootProject.rootDir}/environment.properties"
}

android {
    namespace = "io.taptalk.TapTalkSample"
    def globalConfig = rootProject.extensions.getByName("ext")

    compileSdk 36

    defaultConfig {
        applicationId "io.taptalk.TapTalkSample"
        minSdk 21
        targetSdk 36
        versionCode taptalk_version_code
        versionName taptalk_version_name
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            try {
                Properties props = new Properties()
                def propFile = file(globalConfig.signingProps)
                if (propFile.canRead()) {
                    props.load(new FileInputStream(propFile))

                    if (props != null &&
                        props.containsKey(globalConfig.keystoreFileName) &&
                        props.containsKey(globalConfig.keystorePasswordName) &&
                        props.containsKey(globalConfig.keyAliasName) &&
                        props.containsKey(globalConfig.keyPasswordName)
                    ) {
                        def keystoreFile = file(props[globalConfig.keystoreFileName])
                        if (keystoreFile.canRead()) {
                            storeFile keystoreFile
                            storePassword props[globalConfig.keystorePasswordName]
                            keyAlias props[globalConfig.keyAliasName]
                            keyPassword props[globalConfig.keyPasswordName]
                        }
                        else {
                            println("[GRADLE BUILD ERR]: Keystore file not found: " + props[globalConfig.keystoreFileName])
                            android.buildTypes.release.signingConfig = null
                        }
                    }
                    else {
                        println("[GRADLE BUILD ERR]: File signing.properties found but some entries missing")
                        android.buildTypes.release.signingConfig = null
                    }
                }
                else {
                    println("[GRADLE BUILD ERR]: File signing.properties not found")
                    android.buildTypes.release.signingConfig = null
                }
            }
            catch (ex) {
                throw new InvalidUserDataException("[GRADLE BUILD ERR]: Signing FAILED. Check signing config." + ex.message)
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            minifyEnabled true
            zipAlignEnabled true
            if (project.hasProperty('RELEASE_GOOGLE_MAPS_API_KEY')) {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"${RELEASE_GOOGLE_MAPS_API_KEY}\"")
            }
            else {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"\"")
            }
            if (project.hasProperty('RELEASE_TAPTALK_SDK_APP_KEY_ID')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"${RELEASE_TAPTALK_SDK_APP_KEY_ID}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"\"")
            }
            if (project.hasProperty('RELEASE_TAPTALK_SDK_APP_KEY_SECRET')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"${RELEASE_TAPTALK_SDK_APP_KEY_SECRET}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"\"")
            }
            if (project.hasProperty('RELEASE_TAPTALK_SDK_BASE_URL')) {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"${RELEASE_TAPTALK_SDK_BASE_URL}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"\"")
            }
        }
        staging {
            signingConfig signingConfigs.debug
            debuggable true
            minifyEnabled false
            applicationIdSuffix '.staging'
            versionNameSuffix '-STAGING'
            if (project.hasProperty('STAGING_GOOGLE_MAPS_API_KEY')) {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"${STAGING_GOOGLE_MAPS_API_KEY}\"")
            }
            else {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"\"")
            }
            if (project.hasProperty('STAGING_TAPTALK_SDK_APP_KEY_ID')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"${STAGING_TAPTALK_SDK_APP_KEY_ID}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"\"")
            }
            if (project.hasProperty('STAGING_TAPTALK_SDK_APP_KEY_SECRET')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"${STAGING_TAPTALK_SDK_APP_KEY_SECRET}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"\"")
            }
            if (project.hasProperty('STAGING_TAPTALK_SDK_BASE_URL')) {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"${STAGING_TAPTALK_SDK_BASE_URL}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"\"")
            }
        }
        stagingUpload {
            signingConfig signingConfigs.release
            debuggable false
            minifyEnabled false
            applicationIdSuffix '.staging'
            versionNameSuffix '-STAGING'
            if (project.hasProperty('STAGING_GOOGLE_MAPS_API_KEY')) {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"${STAGING_GOOGLE_MAPS_API_KEY}\"")
            }
            else {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"\"")
            }
            if (project.hasProperty('STAGING_TAPTALK_SDK_APP_KEY_ID')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"${STAGING_TAPTALK_SDK_APP_KEY_ID}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"\"")
            }
            if (project.hasProperty('STAGING_TAPTALK_SDK_APP_KEY_SECRET')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"${STAGING_TAPTALK_SDK_APP_KEY_SECRET}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"\"")
            }
            if (project.hasProperty('STAGING_TAPTALK_SDK_BASE_URL')) {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"${STAGING_TAPTALK_SDK_BASE_URL}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"\"")
            }
        }
        dev {
            signingConfig signingConfigs.debug
            debuggable true
            minifyEnabled false
            applicationIdSuffix '.dev'
            versionNameSuffix '-DEV'
            if (project.hasProperty('DEV_GOOGLE_MAPS_API_KEY')) {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"${DEV_GOOGLE_MAPS_API_KEY}\"")
            }
            else {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"\"")
            }
            if (project.hasProperty('DEV_TAPTALK_SDK_APP_KEY_ID')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"${DEV_TAPTALK_SDK_APP_KEY_ID}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"\"")
            }
            if (project.hasProperty('DEV_TAPTALK_SDK_APP_KEY_SECRET')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"${DEV_TAPTALK_SDK_APP_KEY_SECRET}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"\"")
            }
            if (project.hasProperty('DEV_TAPTALK_SDK_BASE_URL')) {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"${DEV_TAPTALK_SDK_BASE_URL}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"\"")
            }
        }
        devUpload {
            signingConfig signingConfigs.release
            debuggable false
            minifyEnabled false
            applicationIdSuffix '.dev'
            versionNameSuffix '-DEV'
            if (project.hasProperty('DEV_GOOGLE_MAPS_API_KEY')) {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"${DEV_GOOGLE_MAPS_API_KEY}\"")
            }
            else {
                buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"\"")
            }
            if (project.hasProperty('DEV_TAPTALK_SDK_APP_KEY_ID')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"${DEV_TAPTALK_SDK_APP_KEY_ID}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_ID", "\"\"")
            }
            if (project.hasProperty('DEV_TAPTALK_SDK_APP_KEY_SECRET')) {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"${DEV_TAPTALK_SDK_APP_KEY_SECRET}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_APP_KEY_SECRET", "\"\"")
            }
            if (project.hasProperty('DEV_TAPTALK_SDK_BASE_URL')) {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"${DEV_TAPTALK_SDK_BASE_URL}\"")
            }
            else {
                buildConfigField("String", "TAPTALK_SDK_BASE_URL", "\"\"")
            }
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lintOptions {
        disable "Instantiatable"
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

base {
    archivesName = android.defaultConfig.applicationId + "-" + android.defaultConfig.versionName
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //noinspection GradleDependency - Latest available version for minSdk 21
    implementation 'com.google.android.material:material:1.13.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // TapTalk
    implementation project(':taptalk')

    // Glide
    //noinspection NewerVersionAvailable
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    //noinspection NewerVersionAvailable
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    // Stetho
    implementation 'com.facebook.stetho:stetho:1.6.0'
    implementation 'com.facebook.stetho:stetho-okhttp3:1.6.0'

    // Firebase
    //noinspection GradleDependency
    implementation platform('com.google.firebase:firebase-bom:32.8.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
}
